---
pipeline:
    notify:
        image: plugins/slack
        webhook: {slack_webhook}
        channel: tp117
        username: drone
        secrets: [ slack_webhook ]

    build:
        image: node:alpine
        commands:
            - yarn

    test:
        image: node:alpine
        commands:
            - yarn test

    notify:
        image: plugins/slack
        webhook: {slack_webhook}
        channel: tp117
        username: drone
        secrets: [ slack_webhook ]
